ProvaWilliam/Models/Medicos.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;


namespace ProvaWilliam.Models
{
    public class Medicos
    {
        [Key]
        public int id { get; set; }
        public string nome { get; set;}
        public string crm { get; set;}

        public int id_especialidade { get; set; }
        
        [ForeignKey("id_especialidade")]
        public virtual Especialidade Especialidade { get; set; }
    }
}

ProvaWilliam/Controllers/MedicoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProvaWilliam.Infra;
using ProvaWilliam.Models;
using ProvaWilliam.Models.Filter;
using ProvaWilliam.Interface;

namespace ProvaWilliam.Controllers
{
    public class MedicoController : Controller
    {
        private IMedicoService _medicoService;
        private IEspecialidadeService _especialidadeService;
        public MedicoController() { }
        public MedicoController(IMedicoService medicoService, IEspecialidadeService especialidadeService)
        {
            _medicoService = medicoService;
            _especialidadeService = especialidadeService;

        }

        public async Task<ActionResult> Index(int pageNumber = 1, int pageSize = 10)
        {
            ViewBag.respostaDelete = TempData["respostaDelete"];
            ViewBag.respostaMSGSemEspecialidade = TempData["msg_sem_especialidade"];

            var viewModel = await _medicoService.Listagem(pageNumber, pageSize);
            return View(viewModel);
        }




        public async Task<ActionResult> SearchMedicos(FilterMedicos filter)
        {
            var viewModel = await _medicoService.GetMedicoByFilterAsync(filter);
            return View("Index", viewModel);
        }




        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Medicos medicos = await _medicoService.GetMedicoByIdAsync(id.Value);
            if (medicos == null)
            {
                return HttpNotFound();
            }
            return View(medicos);
        }


        public async Task<ActionResult> Create()
        {
            var validaEspecialidade =await _especialidadeService.GetAllAsync();
            if (validaEspecialidade.Count() <= 0)
            {

                TempData["msg_sem_especialidade"] = "Cadastre pelo menos uma especialidade antes de cadastrar os medicos!";
                return RedirectToAction("Index");
            }

            var especialidade = await _especialidadeService.GetAllAsync();
            ViewBag.id_especialidade = new SelectList(especialidade, "id", "descricao");
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "id,nome,crm,id_especialidade")] Medicos medicos)
        {

            

            if (ModelState.IsValid)
            {
                var retorno =await _medicoService.Create(medicos);
                return RedirectToAction("Index");
            }
            var especialidades =await _especialidadeService.GetAllAsync();
            ViewBag.id_especialidade = new SelectList(especialidades, "id", "descricao", medicos.id_especialidade);
            return View(medicos);
        }

        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Medicos medicos = await _medicoService.GetMedicoByIdAsync(id.Value);
            if (medicos == null)
            {
                return HttpNotFound();
            }
            var especialidades = await _especialidadeService.GetAllAsync();
            ViewBag.id_especialidade = new SelectList(especialidades, "id", "descricao", medicos.id_especialidade);
            return View(medicos);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "id,nome,crm,id_especialidade")] Medicos medicos)
        {
            if (ModelState.IsValid)
            {
                var retorno =await _medicoService.Edit(medicos);  
                return RedirectToAction("Index");
            }
            var especialidades = await _especialidadeService.GetAllAsync();
            ViewBag.id_especialidade = new SelectList(especialidades, "id", "descricao", medicos.id_especialidade);
            return View(medicos);
        }

      
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Medicos medicos = await _medicoService.GetMedicoByIdAsync(id.Value);
            if (medicos == null)
            {
                return HttpNotFound();
            }
            return View(medicos);
        }

        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            var resposta = await _medicoService.Delete(id);
            TempData["respostaDelete"] = resposta;
            return RedirectToAction("Index");
        }

        
    }
}

ProvaWilliam/Views/Medico/Create.cshtml
@model ProvaWilliam.Models.Medicos

@{
    ViewBag.Title = "Médicos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Cadastrar médicos</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Médicos</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            Nome
            <div class="col-md-10">
                @Html.EditorFor(model => model.nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
           CRM
            <div class="col-md-10">
                @Html.EditorFor(model => model.crm, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.crm, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
           Especialidade
            <div class="col-md-10">
                @Html.DropDownList("id_especialidade", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_especialidade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10 pt-2">
                <input type="submit" value="Cadastrar" class="btn btn-primary btn-sm" />
            </div>
        </div>
    </div>
}

<div class="pt-2">
    @Html.ActionLink("Retornar", "Index","", new { @class = "btn btn-primary btn-sm" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProvaWilliam/Views/Medico/Delete.cshtml
@model ProvaWilliam.Models.Medicos

@{
    ViewBag.Title = "Deletar médicos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Deletar</h2>

<h3>Realmente quer deletar?</h3>
<div>
    <h4>Médicos</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Especialidade.descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Especialidade.descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.crm)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.crm)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Deletar" class = "btn btn-danger btn-sm" /> |
            @Html.ActionLink("Retornar", "Index","", new { @class = "btn btn-primary btn-sm" })
        </div>
    }
</div>

ProvaWilliam/Views/Medico/Details.cshtml
@model ProvaWilliam.Models.Medicos

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Medicos</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Especialidade.descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Especialidade.descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.crm)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.crm)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.id }, new { @class = "btn btn-primary btn-sm" }) |
    @Html.ActionLink("Retornar", "Index","", new { @class = "btn btn-primary btn-sm" })
</p>

ProvaWilliam/Views/Medico/Edit.cshtml
@model ProvaWilliam.Models.Medicos

@{
    ViewBag.Title = "Editar médicos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar Médicos</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Médicos</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
           Nome
            <div class="col-md-10">
                @Html.EditorFor(model => model.nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
           CRM
            <div class="col-md-10">
                @Html.EditorFor(model => model.crm, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.crm, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Especialidade
            <div class="col-md-10">
                @Html.DropDownList("id_especialidade", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_especialidade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10 pt-2">
                <input type="submit" value="Alterar" class="btn btn-primary btn-sm " />
            </div>
        </div>
    </div>
}

<div class="pt-2">
    @Html.ActionLink("Retornar", "Index","", new { @class = "btn btn-primary btn-sm" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProvaWilliam/Views/Medico/Index.cshtml
@model ProvaWilliam.Models.SearchResultViewModel

@{



    var respostaDelete = ViewBag.respostaDelete as ProvaWilliam.Models.DTOs.RespostaDTO;
    var respostaMSGSemEspecialidade = ViewBag.respostaMSGSemEspecialidade as string;
}

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Medicos</h2>

<div class="row">

<div class="col-md-6">

@if (respostaDelete != null)
{<p style="color:@(respostaDelete.Sucesso?"green":"red")">@respostaDelete.Mensagem</p>}

@using (Html.BeginForm("SearchMedicos", "Medico", FormMethod.Get))
{
    <p>
        Nome: @Html.TextBox("nome", "", new { @class = "form-control" })
        CRM: @Html.TextBox("crm", "", new { @class = "form-control" })
        Especialidade: @Html.DropDownList("id_especialidade",
new SelectList(Enumerable.Empty<SelectListItem>(), "Value", "Text"), "Selecione uma Especialidade", new { @class = "form-control", id = "especialidadeDropdown" })


        <input type="submit" value="Pesquisar" />
    </p>

}
</div>
<div class="col-md-6">


<p>
    @Html.ActionLink("Registrar novo medico", "Create", "", new { @class = "btn btn-primary" })
</p>
@if (!string.IsNullOrEmpty( respostaMSGSemEspecialidade) )
{<p >@respostaMSGSemEspecialidade</p>}

</div>

</div>

<table class="table table-striped table-dark">
    <tr>
        <th>
            Descrição
        </th>
        <th>
            Nome do médico
        </th>
        <th>
            CRM
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.Medicos)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Especialidade.descricao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.crm)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.id }, new { @class = "btn btn-primary btn-sm" }) |
                @Html.ActionLink("Detalhes", "Details", new { id = item.id }, new { @class = "btn btn-primary btn-sm" }) |
                @Html.ActionLink("Deletar", "Delete", new { id = item.id }, new { @class = "btn btn-danger btn-sm" })
            </td>
        </tr>
    }

</table>


<nav aria-label="Page navigation">
    <ul class="pagination">
        @if (Model.CurrentPage > 1)
        {
            <li class="page-item">
                @Html.ActionLink("Anterior", "Index", new { pageNumber = Model.CurrentPage - 1, pageSize = Model.PageSize }, new { @class = "page-link" })
            </li>
        }
        else
        {
            <li class="page-item disabled">
                <span class="page-link">Anterior</span>
            </li>
        }

        @for (int i = 1; i <= Model.TotalPages; i++)
        {
            if (i == Model.CurrentPage)
            {
                <li class="page-item active">
                    <span class="page-link">
                        @i
                    </span>
                </li>
            }
            else
            {
                <li class="page-item">
                    @Html.ActionLink(i.ToString(), "Index", new { pageNumber = i, pageSize = Model.PageSize }, new { @class = "page-link" })
                </li>
            }
        }

        @if (Model.CurrentPage < Model.TotalPages)
        {
            <li class="page-item">
                @Html.ActionLink("Próximo", "Index", new { pageNumber = Model.CurrentPage + 1, pageSize = Model.PageSize }, new { @class = "page-link" })
            </li>
        }
        else
        {
            <li class="page-item disabled">
                <span class="page-link">Próximo</span>
            </li>
        }
    </ul>
</nav>

<script src="~/Scripts/scripstsViews/jquery.min.js"></script>
<script src="~/Scripts/scripstsViews/FuncaoBuscaEspecialidade.js"></script>